# Anime Prediction with Cosine similarity

In [1]:
#load required libraries
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

### Upload nad explore the data set

In [2]:
#Upload the dataset prepared
df=pd.read_csv("Anime_dataset_all.csv")
df

Title  \
0                       Fullmetal Alchemist: Brotherhood   
1                                     Gintama: The Final   
2                     Shingeki no Kyojin Season 3 Part 2   
3                                            Steins;Gate   
4                               Fruits Basket: The Final   
...                                                  ...   
18344  Jashin Shoukan: Inran Kyonyuu Oyako Ikenie Gis...   
18345                                   Konbini Shoujo Z   
18346                                   Korogashi Ryouta   
18347                           Kuroinu II The Animation   
18348                   Maou Evelogia ni Mi wo Sasage yo   

                                   English  \
0       Fullmetal Alchemist: Brotherhood     
1                                      NaN   
2        Attack on Titan Season 3 Part 2     
3                            Steins;Gate     
4                                      NaN   
...                                    ...   
18344                                  NaN   
18345                                  NaN   
18346                                  NaN   
18347                                  NaN   
18348                                  NaN   

                                                Synonyms  \
0       Hagane no Renkinjutsushi: Fullmetal Alchemist...   
1                                                    NaN   
2                                                    NaN   
3                                                    NaN   
4       Fruits Basket 3rd Season, Fruits Basket (2019...   
...                                                  ...   
18344                                                NaN   
18345                                                NaN   
18346                                                NaN   
18347                                                NaN   
18348                                                NaN   

                            Japanese   Type     Episodes           Status  \
0       鋼の錬金術師 FULLMETAL ALCHEMIST       TV           64  Finished Airing   
1                     銀魂 THE FINAL    Movie            1  Finished Airing   
2             進撃の巨人 Season3 Part.2       TV           10  Finished Airing   
3                      STEINS;GATE       TV           24  Finished Airing   
4              フルーツバスケット The Final       TV           13  Finished Airing   
...                              ...    ...          ...              ...   
18344             邪娠娼館―淫乱巨乳母娘生贄儀式―      OVA            2    Not yet aired   
18345                      コンビニ少女Z      OVA    Unknown      Not yet aired   
18346                       ころがし涼太      OVA            3  Finished Airing   
18347     黒獣[クロイヌ]II THE ANIMATION      OVA    Unknown      Not yet aired   
18348                魔王イブロギアに身を捧げよ       TV    Unknown      Not yet aired   

                              Aired    Premiered                    Broadcast  \
0        Apr 5, 2009 to Jul 4, 2010  Spring 2009     Sundays at 17:00 (JST)     
1                       Jan 8, 2021          NaN                          NaN   
2       Apr 29, 2019 to Jul 1, 2019  Spring 2019     Mondays at 00:10 (JST)     
3       Apr 6, 2011 to Sep 14, 2011  Spring 2011  Wednesdays at 02:05 (JST)     
4       Apr 6, 2021 to Jun 29, 2021  Spring 2021    Tuesdays at 01:30 (JST)     
...                             ...          ...                          ...   
18344                   Sep 3, 2021          NaN                          NaN   
18345                 Not available          NaN                          NaN   
18346  Nov 21, 1990 to Nov 21, 1991          NaN                          NaN   
18347             Aug 27, 2021 to ?          NaN                          NaN   
18348                 Oct 2021 to ?    Fall 2021                    Unknown     

       ...        Source                                             Genres  \
0      ...         Manga  Action, Military, Adventure, Comedy, Drama, Ma...   


In [3]:
df.shape

(18349, 23)

In [4]:
df.columns

Index(['Title', 'English', 'Synonyms', 'Japanese', 'Type', 'Episodes',
       'Status', 'Aired', 'Premiered', 'Broadcast', 'Producers', 'Licensors',
       'Studios', 'Source', 'Genres', 'Duration', 'Rating', 'Score', 'Ranked',
       'Popularity', 'Members', 'Favorites', 'link'],
      dtype='object')

In [5]:
df.drop(['Aired','Premiered','Broadcast','Duration','Favorites','link'],axis = 1,inplace=True)

In [6]:
df.isnull().sum()

Title             0
English       11023
Synonyms       7351
Japanese         65
Type              0
Episodes          0
Status            0
Producers         0
Licensors         0
Studios           0
Source            0
Genres            0
Rating            0
Score          5239
Ranked            0
Popularity        0
Members           0
dtype: int64

In [7]:
#Dealing with empty cells
features = ['Licensors', 'Genres', 'Studios', 'Rating','Score']

for feature in features:
    df[feature] = df[feature].fillna('')

In [8]:
df.dtypes

Title         object
English       object
Synonyms      object
Japanese      object
Type          object
Episodes      object
Status        object
Producers     object
Licensors     object
Studios       object
Source        object
Genres        object
Rating        object
Score         object
Ranked        object
Popularity    object
Members       object
dtype: object

In [9]:
#converting the datatype so combine all the required columns to prepare cosine simarity matrix
df.Rating = df.Rating.astype(str)
df.Score=df.Score.astype(str)

In [58]:
def combined_features(row):
    return row['Licensors']+" "+row['Genres']+" "+row['Studios']+" "+row['Rating']+" "+row['Score']+" "+row['Type']
df["combined_features"] = df.apply(combined_features, axis =1)

In [59]:
#Combined all required columns 
df.head()

Title  \
Index                                       
0        Fullmetal Alchemist: Brotherhood   
1                      Gintama: The Final   
2      Shingeki no Kyojin Season 3 Part 2   
3                             Steins;Gate   
4                Fruits Basket: The Final   

                                   English  \
Index                                        
0       Fullmetal Alchemist: Brotherhood     
1                                      NaN   
2        Attack on Titan Season 3 Part 2     
3                            Steins;Gate     
4                                      NaN   

                                                Synonyms  \
Index                                                      
0       Hagane no Renkinjutsushi: Fullmetal Alchemist...   
1                                                    NaN   
2                                                    NaN   
3                                                    NaN   
4       Fruits Basket 3rd Season, Fruits Basket (2019...   

                            Japanese   Type Episodes           Status  \
Index                                                                   
0       鋼の錬金術師 FULLMETAL ALCHEMIST       TV       64  Finished Airing   
1                     銀魂 THE FINAL    Movie        1  Finished Airing   
2             進撃の巨人 Season3 Part.2       TV       10  Finished Airing   
3                      STEINS;GATE       TV       24  Finished Airing   
4              フルーツバスケット The Final       TV       13  Finished Airing   

                                               Producers  \
Index                                                      
0      Aniplex, Square Enix, Mainichi Broadcasting Sy...   
1                          TV Tokyo, Warner Bros. Japan    
2      Production I.G, Dentsu, Mainichi Broadcasting ...   
3      Frontier Works, Media Factory, Movic, AT-X, Ka...   
4      TV Tokyo, TV Osaka, Nihon Ad Systems, Hakusens...   

                             Licensors                 Studios        Source  \
Index                                                                          
0      Funimation, Aniplex of America                   Bones          Manga   
1                         Eleven Arts   Bandai Namco Pictures          Manga   
2                          Funimation              Wit Studio          Manga   
3                          Funimation               White Fox   Visual novel   
4                          Funimation       TMS Entertainment          Manga   

                                                  Genres  \
Index                                                      
0      Action, Military, Adventure, Comedy, Drama, Ma...   
1      Action, Sci-Fi, Comedy, Historical, Parody, Dr...   
2      Action, Drama, Fantasy, Military, Mystery, Sho...   
3                 Sci-Fi, Psychological, Drama, Thriller   
4      Slice of Life, Comedy, Supernatural, Drama, Ro...   

                               Rating              Score Ranked Popularity  \
Index                                                                        
0      R - 17+ (violence & profanity)              9.161   #122         #3   
1           PG-13 - Teens 13 or older              9.101   #222      #2256   
2      R - 17+ (violence & profanity)              9.101   #322        #36   
3           PG-13 - Teens 13 or older              9.101   #422        #11   
4           PG-13 - Teens 13 or older  9.091000000000001   #522       #712   

         Members                                  combined_features  
Index                                                                
0      25,72,173  Funimation, Aniplex of America  Action, Milita...  
1         59,478  Eleven Arts  Action, Sci-Fi, Comedy, Historica...  
2      14,82,102  Funimation  Action, Drama, Fantasy, Military, ...  
3      20,16,145  Funimation  Sci-Fi, Psychological, Drama, Thri...  
4       2,36,860  Funimation  Slice of Life, Comedy, Supernatura...

## Creating recommendation model with cosine similarity 

Using sklearn.feature_extraction module converting the "Combined features" to the format supported by machine learning algorithms. Using CountVectorizer’s fit.tranform to count the number of texts and print the transformed matrix count_matrix into an array for better understanding.

In [60]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["combined_features"])
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


With Cosine Similarity from Sklearn calculating the similarity between two anime. Cosine similarity is a metric used to measure how similar two items are. The output value ranges from 0–1 where 0 means no similarity and 1 means that both the items are 100% similar. 

In [61]:
cosine_sim = cosine_similarity(count_matrix)

#### Taking user input anime name and recommending 10 titles with cosine similarity

In [62]:
def get_index_from_title(a): #Getting indx of title that user has given
    return df.index[df.Title == x].values[0]

def get_title_from_index(index): # Getting the recommended titles with index
    return df[df.index == index]["Title"].values[0]


In [63]:
def print_anime_recommendation(Anime_user_likes):
    Anime_index = get_index_from_title(Anime_user_likes)
    similar_anime = list(enumerate(cosine_sim[Anime_index]))
    sorted_similar_anime = sorted(similar_anime, key=lambda x:x[1], reverse=True)
    i=0
    for anime in sorted_similar_anime:
        print(get_title_from_index(anime[0]))
        i=i+1
        if i>10:
            break

In [67]:
x=input()
print_anime_recommendation(x)

 One Piece


One Piece
One Piece Movie 14: Stampede
One Piece: Episode of East Blue - Luffy to 4-nin no Nakama no Daibouken
One Piece: Episode of Sabo - 3 Kyoudai no Kizuna Kiseki no Saikai to Uketsugareru Ishi
One Piece: Episode of Sorajima
Dragon Ball Z
Dragon Ball Kai
Dragon Ball Kai (2014)
Dragon Ball Super
One Piece: Adventure of Nebulandia
Dragon Ball Movie 1: Shen Long no Densetsu


## Conclusion: 

#### Given input title as "One Piece." Above are the titles suggested as recommendation based on the input.